name: Github Actions 실행

on:
  push:
    branches:
      - main

jobs:
  My-Deploy-job:
    runs-on: ubuntu-latest


    steps:
      - name: Hello World 찍기
        run: echo "Hello World"

      - name: 두 번째 step
        run: |
          echo "두 번째 step"
          echo "여러 줄을 출력할 수 있습니다."
